"""Wheel comparison logic.

Compares two wheels (upstream vs. downstream rebuild) by examining
their ZIP central directory metadata.  CRC-32 checksums and file
sizes are compared without downloading file contents, making the
initial comparison very efficient.
"""

from __future__ import annotations

import asyncio
import dataclasses
import enum
import logging
import posixpath
import re
import typing
import zipfile
from typing import Any

import packaging.utils
from packaging.metadata import parse_email
from packaging.requirements import Requirement
from packaging.specifiers import SpecifierSet
from packaging.version import InvalidVersion, Version

from retread._errors import InvalidWheelError
from retread._platform import PlatformWarning, check_platform_abi
from retread._record import RecordMismatch, check_records
from retread._resolve import _parse_name_version, _wheel_basename

if typing.TYPE_CHECKING:
    import collections.abc
    import pathlib

    from zipwire import AsyncRemoteZip, SyncRemoteZip

logger = logging.getLogger(__name__)


class Severity(enum.Enum):
    EXPECTED = "expected"
    NOTICE = "notice"
    ERROR = "error"


class Classification(enum.Enum):
    METADATA = "dist-info METADATA"
    RECORD = "dist-info RECORD"
    WHEEL = "dist-info WHEEL"
    SBOM = "sbom"
    LICENSE = "license"
    DIST_INFO = "dist-info"
    AUDITWHEEL = "auditwheel"
    DATA = "data"
    DATA_SCRIPTS = "data scripts"
    EXTENSION_MODULE = "extension module"
    STATIC_LIBRARY = "static library"
    JAR = "jar"
    VERSION_FILE = "version file"
    NAMESPACE_PKG_PTH = "namespace pkg pth"
    GENERATED_PROTOBUF = "generated protobuf"
    GENERATED_ANTLR = "generated antlr"
    GENERATED_C = "generated c/c++"  # probably Cython-generated or vendored
    GENERATED_BUILD_CONFIG = "generated build config"
    TEST = "test"
    OTHER = "other"


_SHARED_LIB_RE = re.compile(r"\.so(\.[0-9.]+)?$")
_STATIC_LIB_RE = re.compile(r"/lib[^/]+\.a$")
_EXT_SUFFIX_RE = re.compile(r"(\.cpython-[^/]+\.so|\.abi3t?\.so|\.so)$")


def _is_shared_library(filename: str) -> bool:
    """Return True if *filename* looks like a shared library.

    Matches both unversioned (``foo.so``) and versioned
    (``libfoo.so.1.2.3``) shared-object names.
    """
    return _SHARED_LIB_RE.search(filename) is not None


def _is_static_library(filename: str) -> bool:
    """Return True if *filename* looks like a static archive (``lib*.a``)."""
    return _STATIC_LIB_RE.search(filename) is not None


_VERSION_BASENAMES = frozenset(
    {
        "_version.py",
        "__version__.py",
        "version.py",
        "__config__.py",
    }
)


def _is_version_file(filename: str) -> bool:
    """Return True if *filename* is an auto-generated version file."""
    return posixpath.basename(filename) in _VERSION_BASENAMES


def _is_test_file(filename: str) -> bool:
    """Return True if *filename* is inside a test directory.

    Matches ``test/`` and ``tests/`` path components at any depth.
    """
    parts = filename.split("/")
    return any(part in ("test", "tests") for part in parts)


_PROTOBUF_SUFFIXES = ("_pb2.py", "_pb2_grpc.py", "_pb2.pyi", "_pb2_grpc.pyi")
_ANTLR_SUFFIXES = ("Lexer.py", "Parser.py", "ParserListener.py", "ParserVisitor.py")
# C/C++ source and header file suffixes:
#   .c, .cpp     - C/C++ source (often Cython-generated)
#   .h, .hpp     - C/C++ headers
#   .inc         - textual includes (MLIR TableGen, protobuf)
#   .inl         - C++ inline implementation headers
#   .cuh         - CUDA C++ headers
_C_SOURCE_SUFFIXES = (".c", ".cpp", ".cuh", ".h", ".hpp", ".inc", ".inl")
_BUILD_CONFIG_SUFFIXES = (".cmake", ".pc")


def _is_protobuf_generated(filename: str) -> bool:
    """Return True if *filename* looks like a protobuf-generated file.

    Matches ``*_pb2.py``, ``*_pb2_grpc.py`` and their ``.pyi`` stubs.
    """
    return filename.endswith(_PROTOBUF_SUFFIXES)


def _is_antlr_generated(filename: str) -> bool:
    """Return True if *filename* looks like an ANTLR-generated file.

    Matches ``*Lexer.py``, ``*Parser.py``, ``*ParserListener.py``,
    ``*ParserVisitor.py`` inside a ``grammar/gen/`` directory.
    """
    if "grammar/gen/" not in filename:
        return False
    basename = posixpath.basename(filename)
    return basename.endswith(_ANTLR_SUFFIXES)


def _is_c_source(filename: str) -> bool:
    """Return True if *filename* is a C/C++ source or header file.

    Matches ``.c``, ``.cpp``, ``.h``, ``.hpp``.  These are almost
    always Cython-generated or vendored sources that differ between
    generator versions.

    If this heuristic produces false positives in the future, a more
    precise approach would be to read the file header and look for the
    ``/* Generated by Cython */`` comment.
    """
    return filename.endswith(_C_SOURCE_SUFFIXES)


def _is_build_config(filename: str) -> bool:
    """Return True if *filename* is a build configuration file.

    Matches CMake configs (``.cmake``) and pkg-config files (``.pc``).
    These are auto-generated during the build and embed build-specific
    paths that differ between upstream and downstream.
    """
    return filename.endswith(_BUILD_CONFIG_SUFFIXES)


# A ``lib/python3.*/site-packages/`` path component sequence is the
# hallmark of a virtual environment that was accidentally swept into
# the wheel (e.g. a ``.venv/`` directory picked up by the build).
_VENV_SITE_PACKAGES_RE = re.compile(r"(?:^|/)lib/python3\.[^/]*/site-packages/")


def _is_bundled_venv_file(filename: str) -> bool:
    """Return True if *filename* lives inside a bundled virtual environment."""
    return _VENV_SITE_PACKAGES_RE.search(filename) is not None


def _find_bundled_venvs(infos: dict[str, Any]) -> list[str]:
    """Find bundled virtual environments inside a wheel.

    Scans *infos* for files under a ``lib/python3.*/site-packages/``
    directory, which indicates a virtual environment was packaged into
    the wheel by mistake.

    Returns a sorted list of the distinct ``.../site-packages/``
    directory prefixes found (one per bundled environment).
    """
    prefixes: set[str] = set()
    for fname in infos:
        m = _VENV_SITE_PACKAGES_RE.search(fname)
        if m is not None:
            prefixes.add(fname[: m.end()])
    return sorted(prefixes)


def _extension_stem(filename: str) -> str | None:
    """Extract the module stem from an extension module filename.

    Returns the path without the ABI-specific suffix, or ``None`` if
    the filename is not a recognized extension module.

    Examples::

        foo/_bar.cpython-312-x86_64-linux-gnu.so  ->  foo/_bar
        foo/_bar.abi3.so                           ->  foo/_bar
        foo/_bar.abi3t.so                          ->  foo/_bar
        foo/_bar.so                                ->  foo/_bar
        foo/bar.py                                 ->  None
    """
    m = _EXT_SUFFIX_RE.search(filename)
    if m:
        return filename[: m.start()]
    return None


def _pair_extension_modules(
    only_upstream: list[str],
    only_downstream: list[str],
) -> frozenset[str]:
    """Find extension modules that differ only in ABI suffix.

    When upstream has e.g. ``foo.abi3.so`` and downstream has
    ``foo.cpython-312-x86_64-linux-gnu.so``, they are the same
    module linked against different ABIs.

    Returns the set of filenames (from both sides) that are paired.
    """
    up_stems: dict[str, str] = {}
    for fname in only_upstream:
        stem = _extension_stem(fname)
        if stem is not None:
            up_stems[stem] = fname

    paired: set[str] = set()
    for fname in only_downstream:
        stem = _extension_stem(fname)
        if stem is not None and stem in up_stems:
            paired.add(up_stems[stem])
            paired.add(fname)

    return frozenset(paired)


def _pair_prefixed_files(
    only_upstream: list[str],
    only_downstream: list[str],
    up_prefix: str,
    down_prefix: str,
    upstream_infos: dict[str, Any],
    downstream_infos: dict[str, Any],
) -> tuple[frozenset[str], frozenset[str]]:
    """Pair files that differ only in a directory prefix.

    When upstream and downstream use different prefixes for the same
    logical directory (e.g. ``ImageHash-4.3.2.data/`` vs
    ``imagehash-4.3.2.data/``, or ``foo-1.0.dist-info/`` vs
    ``foo-1.0+local.dist-info/``), files that share the same path
    after the prefix are paired.

    Returns ``(identical_pairs, different_pairs)`` -- two frozensets
    of filenames.  *identical_pairs* contains files whose CRC and size
    match (EXPECTED); *different_pairs* contains files whose content
    differs (severity determined by caller).
    """
    if up_prefix == down_prefix:
        return frozenset(), frozenset()

    up_by_rest: dict[str, str] = {}
    for fname in only_upstream:
        if fname.startswith(up_prefix):
            up_by_rest[fname[len(up_prefix) :]] = fname

    identical: set[str] = set()
    different: set[str] = set()
    for fname in only_downstream:
        if fname.startswith(down_prefix):
            rest = fname[len(down_prefix) :]
            up_fname = up_by_rest.get(rest)
            if up_fname is None:
                continue
            u_info = upstream_infos[up_fname]
            d_info = downstream_infos[fname]
            if u_info.CRC == d_info.CRC and u_info.file_size == d_info.file_size:
                identical.add(up_fname)
                identical.add(fname)
            else:
                different.add(up_fname)
                different.add(fname)

    return frozenset(identical), frozenset(different)


def _is_auditwheel_lib(filename: str) -> bool:
    """Return True if *filename* is inside an auditwheel bundle directory.

    auditwheel vendors external shared libraries into a ``*.libs/``
    directory (e.g. ``Pillow.libs/libpng16-...so.16.58.0``).  These
    files are expected to appear or disappear between upstream and
    downstream builds.
    """
    parts = filename.split("/")
    return any(part.endswith(".libs") for part in parts)


def _find_dist_info_name(
    infos: dict[str, Any],
    dist: str,
    version: str,
) -> str:
    """Find the distribution name used in the dist-info directory.

    The dist-info directory name inside a wheel may differ in casing
    or punctuation from the wheel filename.  This function scans
    *infos* for a root-level ``{name}-{version}.dist-info/`` entry
    whose canonical name matches *dist* and returns the *name* portion
    actually used.

    Examples of real-world mismatches between wheel filename and
    dist-info directory:

    * ``InquirerPy-0.3.4.whl`` → ``inquirerpy-0.3.4.dist-info/``
    * ``scons-4.5.2.whl`` → ``SCons-4.5.2.dist-info/``
    * ``jpype1-1.5.0.whl`` → ``JPype1-1.5.0.dist-info/``
    * ``jaraco_classes-3.4.0.whl`` → ``jaraco.classes-3.4.0.dist-info/``

    Falls back to *dist* unchanged when no matching directory is found.
    """
    canonical = packaging.utils.canonicalize_name(dist)
    suffix = f"-{version}.dist-info"
    for filename in infos:
        if filename.count("/") != 1:
            continue
        dir_part, _rest = filename.split("/", 1)
        if not dir_part.endswith(suffix):
            continue
        name_part = dir_part.removesuffix(suffix)
        if name_part and packaging.utils.canonicalize_name(name_part) == canonical:
            return name_part
    return dist


def _classify_file(
    filename: str, *, dist: str, version: str, missing: bool = False
) -> tuple[Severity, Classification]:
    """Classify a file difference with a severity and classification label.

    Always-expected differences (RECORD, WHEEL, shared libraries, data
    scripts) are EXPECTED; other known dist-info differences are NOTICE;
    everything else is an ERROR.

    When *missing* is True the file is only present on one side of the
    comparison.  A shared library that is absent is an error unless it
    lives in an auditwheel bundle directory (``*.libs/``).

    *dist* and *version* are the distribution name and version extracted
    verbatim from the wheel filename (not normalised).

    Returns a ``(Severity, Classification)`` tuple.
    """
    dist_info = f"{dist}-{version}.dist-info/"
    data = f"{dist}-{version}.data/"
    # {name}-{version}.dist-info/
    if filename.startswith(dist_info):
        rest = filename[len(dist_info) :]
        if rest == "RECORD":
            return Severity.EXPECTED, Classification.RECORD
        if rest == "WHEEL":
            return Severity.EXPECTED, Classification.WHEEL
        if rest == "METADATA":
            return Severity.NOTICE, Classification.METADATA
        if rest.startswith("sboms/"):
            return Severity.NOTICE, Classification.SBOM
        if rest.startswith("licenses/"):
            return Severity.NOTICE, Classification.LICENSE
        return Severity.NOTICE, Classification.DIST_INFO
    # {name}-{version}.data/{subdir}/
    if filename.startswith(data):
        rest = filename[len(data) :]
        if rest.startswith("scripts/"):
            if missing:
                return Severity.ERROR, Classification.DATA_SCRIPTS
            return Severity.EXPECTED, Classification.DATA_SCRIPTS
        if missing:
            return Severity.ERROR, Classification.DATA
        return Severity.NOTICE, Classification.DATA
    # auditwheel-bundled shared libraries (*.libs/)
    if _is_auditwheel_lib(filename):
        return Severity.NOTICE, Classification.AUDITWHEEL
    # Test directories (test/ or tests/): differences and missing files
    # inside test suites are not meaningful for rebuild comparison.
    if _is_test_file(filename):
        return Severity.NOTICE, Classification.TEST
    # Shared library binaries (.so) not in *.libs/
    if _is_shared_library(filename):
        if missing:
            return Severity.ERROR, Classification.EXTENSION_MODULE
        # Binary difference in an .so present on both sides is expected
        return Severity.EXPECTED, Classification.EXTENSION_MODULE
    # Static archive libraries (lib*.a)
    if _is_static_library(filename):
        if missing:
            return Severity.ERROR, Classification.STATIC_LIBRARY
        return Severity.EXPECTED, Classification.STATIC_LIBRARY
    # Java archives (.jar)
    if filename.endswith(".jar"):
        if missing:
            return Severity.ERROR, Classification.JAR
        return Severity.EXPECTED, Classification.JAR
    if _is_version_file(filename):
        return Severity.NOTICE, Classification.VERSION_FILE
    # Legacy namespace package .pth files (superseded by PEP 420
    # implicit namespace packages).  The filename embeds the build-time
    # Python version, so it always differs between upstream and rebuild.
    if filename.endswith("-nspkg.pth"):
        return Severity.EXPECTED, Classification.NAMESPACE_PKG_PTH
    # Auto-generated source files (protobuf, ANTLR) differ when
    # rebuilt with a different generator version.
    if _is_protobuf_generated(filename):
        return Severity.NOTICE, Classification.GENERATED_PROTOBUF
    if _is_antlr_generated(filename):
        return Severity.NOTICE, Classification.GENERATED_ANTLR
    if _is_c_source(filename):
        return Severity.NOTICE, Classification.GENERATED_C
    # Build configuration files (CMake, pkg-config)
    if _is_build_config(filename):
        return Severity.NOTICE, Classification.GENERATED_BUILD_CONFIG
    return Severity.ERROR, Classification.OTHER


@dataclasses.dataclass(frozen=True, slots=True)
class FileEntry:
    """A file present only in one side of the comparison."""

    filename: str
    severity: Severity
    classification: Classification


@dataclasses.dataclass(frozen=True, slots=True)
class FileDiff:
    """A file that differs between upstream and downstream wheels."""

    filename: str
    upstream_size: int
    downstream_size: int
    upstream_crc32: int
    downstream_crc32: int
    severity: Severity
    classification: Classification


@dataclasses.dataclass(frozen=True, slots=True)
class VenvBundle:
    """A virtual environment accidentally bundled into a wheel.

    A wheel should never contain a virtual environment.  Files under a
    ``lib/python3.*/site-packages/`` directory indicate a ``.venv`` or
    similar directory was swept into the build.  Bundling one upstream
    is a NOTICE (a pre-existing upstream packaging bug); reproducing it
    downstream is an ERROR.
    """

    side: str  # "upstream" or "downstream"
    severity: Severity
    path: str  # the site-packages directory prefix


@dataclasses.dataclass(frozen=True, slots=True)
class MetadataFieldDiff:
    """A normalized set difference for a multi-value METADATA field.

    Reports the entries of a repeated METADATA field (``Requires-Dist``
    or ``Provides-Extra``) that appear on only one side after
    normalization, so that cosmetic differences (whitespace, ordering,
    name spelling) are ignored.
    """

    field: str  # e.g. "Requires-Dist" or "Provides-Extra"
    only_upstream: tuple[str, ...]
    only_downstream: tuple[str, ...]


@dataclasses.dataclass(frozen=True, slots=True)
class WheelComparison:
    """Result of comparing an upstream wheel to a downstream rebuild.

    Attributes:
        upstream: Identifier (URL or path) of the upstream wheel.
        downstream: Identifier (URL or path) of the downstream rebuild.
        upstream_wheel: Wheel filename of the upstream wheel.
        downstream_wheel: Wheel filename of the downstream rebuild.
        dist: Distribution name extracted from the wheel filenames.
        upstream_version: Version from the upstream wheel filename.
        downstream_version: Version from the downstream wheel filename.
            Usually identical to *upstream_version* but may differ when
            local-version segments differ (e.g. ``1.0+cpu`` vs ``1.0``).
        only_upstream: Files present only in the upstream wheel.
        only_downstream: Files present only in the downstream rebuild.
        different: Files present in both but with different content.
        identical: Files present in both with matching content.
        metadata_field_diffs: Normalized differences in repeated METADATA
            fields (``Requires-Dist``, ``Provides-Extra``); each entry
            lists the values present on only one side.
    """

    upstream: str
    downstream: str
    upstream_wheel: str
    downstream_wheel: str
    dist: str
    upstream_version: Version
    downstream_version: Version
    only_upstream: tuple[FileEntry, ...]
    only_downstream: tuple[FileEntry, ...]
    different: tuple[FileDiff, ...]
    identical: tuple[str, ...]
    record_mismatches: tuple[RecordMismatch, ...] = ()
    platform_warnings: tuple[PlatformWarning, ...] = ()
    venv_bundles: tuple[VenvBundle, ...] = ()
    metadata_field_diffs: tuple[MetadataFieldDiff, ...] = ()
    upstream_dist: str = ""
    downstream_dist: str = ""

    def __post_init__(self) -> None:
        if not self.upstream_dist:
            object.__setattr__(self, "upstream_dist", self.dist)
        if not self.downstream_dist:
            object.__setattr__(self, "downstream_dist", self.dist)

    @property
    def is_identical(self) -> bool:
        """Return True if the wheels are identical.

        Bundled virtual environment files are excluded from the per-file
        diff (see :attr:`venv_bundles`), so their presence is checked
        here instead: a venv bundled on only one side means the wheels
        differ.
        """
        if self.only_upstream or self.only_downstream or self.different:
            return False
        up_venvs = {b.path for b in self.venv_bundles if b.side == "upstream"}
        down_venvs = {b.path for b in self.venv_bundles if b.side == "downstream"}
        return up_venvs == down_venvs

    @property
    def has_errors(self) -> bool:
        """Return True if any difference is classified as an error."""
        return (
            any(entry.severity is Severity.ERROR for entry in self.only_upstream)
            or any(entry.severity is Severity.ERROR for entry in self.only_downstream)
            or any(diff.severity is Severity.ERROR for diff in self.different)
            or bool(self.record_mismatches)
            or bool(self.platform_warnings)
            or any(bundle.severity is Severity.ERROR for bundle in self.venv_bundles)
        )

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable dict representation of the comparison."""
        return {
            "upstream": self.upstream,
            "downstream": self.downstream,
            "upstream_wheel": self.upstream_wheel,
            "downstream_wheel": self.downstream_wheel,
            "is_identical": self.is_identical,
            "has_errors": self.has_errors,
            "only_upstream": [
                {
                    "filename": e.filename,
                    "side": "upstream",
                    "severity": e.severity.value,
                    "classification": e.classification.value,
                }
                for e in self.only_upstream
            ],
            "only_downstream": [
                {
                    "filename": e.filename,
                    "side": "downstream",
                    "severity": e.severity.value,
                    "classification": e.classification.value,
                }
                for e in self.only_downstream
            ],
            "different": [
                {
                    "filename": d.filename,
                    "upstream_size": d.upstream_size,
                    "downstream_size": d.downstream_size,
                    "upstream_crc32": d.upstream_crc32,
                    "downstream_crc32": d.downstream_crc32,
                    "severity": d.severity.value,
                    "classification": d.classification.value,
                }
                for d in self.different
            ],
            "identical": list(self.identical),
            "record_mismatches": [
                {"side": w.side, "message": w.message} for w in self.record_mismatches
            ],
            "platform_warnings": [
                {"side": w.side, "message": w.message} for w in self.platform_warnings
            ],
            "venv_bundles": [
                {"side": b.side, "severity": b.severity.value, "path": b.path}
                for b in self.venv_bundles
            ],
            "metadata_field_diffs": [
                {
                    "field": d.field,
                    "only_upstream": list(d.only_upstream),
                    "only_downstream": list(d.only_downstream),
                }
                for d in self.metadata_field_diffs
            ],
        }


def _detect_venv_bundles(
    upstream_infos: dict[str, Any],
    downstream_infos: dict[str, Any],
) -> tuple[VenvBundle, ...]:
    """Detect virtual environments accidentally bundled into either wheel.

    Files under a ``lib/python3.*/site-packages/`` directory indicate a
    virtual environment was packaged into the wheel by mistake.  This is
    a NOTICE for the upstream wheel (a pre-existing upstream packaging
    bug) and an ERROR for the downstream rebuild, which must not
    reproduce the mistake.
    """
    bundles: list[VenvBundle] = []
    for side, infos, severity in (
        ("upstream", upstream_infos, Severity.NOTICE),
        ("downstream", downstream_infos, Severity.ERROR),
    ):
        for path in _find_bundled_venvs(infos):
            logger.info("bundled venv [%s]: %s", side, path)
            bundles.append(VenvBundle(side=side, severity=severity, path=path))
    return tuple(bundles)


def _read_record(
    infos: dict[str, Any],
    read: collections.abc.Callable[[str], bytes],
    record_path: str,
) -> bytes | None:
    """Read a RECORD file if it exists, otherwise return ``None``."""
    if record_path not in infos:
        return None
    return read(record_path)


def compare_wheels(
    upstream: SyncRemoteZip,
    downstream: SyncRemoteZip,
) -> WheelComparison:
    """Compare two wheels using their ZIP central directory metadata.

    Both ``upstream`` and ``downstream`` must already be open
    (central directory fetched).  Comparison uses CRC-32 checksums
    and uncompressed sizes from the central directory, so no file
    content is downloaded.
    """
    upstream_infos = {info.filename: info for info in upstream.infolist() if not info.is_dir()}
    downstream_infos = {info.filename: info for info in downstream.infolist() if not info.is_dir()}
    result = _compare(
        upstream=upstream.url,
        downstream=downstream.url,
        upstream_infos=upstream_infos,
        downstream_infos=downstream_infos,
    )
    result = _check_metadata(result, upstream.read, downstream.read)
    up_di = f"{result.upstream_dist}-{result.upstream_version}.dist-info"
    down_di = f"{result.downstream_dist}-{result.downstream_version}.dist-info"
    result = check_records(
        result,
        upstream_infos=upstream_infos,
        downstream_infos=downstream_infos,
        upstream_record=_read_record(upstream_infos, upstream.read, f"{up_di}/RECORD"),
        downstream_record=_read_record(downstream_infos, downstream.read, f"{down_di}/RECORD"),
    )
    result = check_platform_abi(
        result,
        upstream_infos=upstream_infos,
        downstream_infos=downstream_infos,
        upstream_wheel=_read_record(upstream_infos, upstream.read, f"{up_di}/WHEEL"),
        downstream_wheel=_read_record(downstream_infos, downstream.read, f"{down_di}/WHEEL"),
        upstream_metadata=_read_record(upstream_infos, upstream.read, f"{up_di}/METADATA"),
        downstream_metadata=_read_record(downstream_infos, downstream.read, f"{down_di}/METADATA"),
    )
    return result


async def async_compare_wheels(
    upstream: AsyncRemoteZip,
    downstream: AsyncRemoteZip,
) -> WheelComparison:
    """Async version of :func:`compare_wheels`."""
    upstream_infos = {info.filename: info for info in upstream.infolist() if not info.is_dir()}
    downstream_infos = {info.filename: info for info in downstream.infolist() if not info.is_dir()}
    result = _compare(
        upstream=upstream.url,
        downstream=downstream.url,
        upstream_infos=upstream_infos,
        downstream_infos=downstream_infos,
    )

    up_di = f"{result.upstream_dist}-{result.upstream_version}.dist-info"
    down_di = f"{result.downstream_dist}-{result.downstream_version}.dist-info"
    upstream_metadata = f"{up_di}/METADATA"
    downstream_metadata = f"{down_di}/METADATA"
    upstream_record = f"{up_di}/RECORD"
    downstream_record = f"{down_di}/RECORD"
    upstream_wheel_path = f"{up_di}/WHEEL"
    downstream_wheel_path = f"{down_di}/WHEEL"

    # Find METADATA in `different` (same-version case)
    metadata_diffs = [diff for diff in result.different if diff.filename == upstream_metadata]

    # Detect cross-version METADATA (different-version case)
    has_cross_metadata = (
        upstream_metadata != downstream_metadata
        and any(e.filename == upstream_metadata for e in result.only_upstream)
        and any(e.filename == downstream_metadata for e in result.only_downstream)
    )

    # Pre-fetch all needed METADATA, RECORD, and WHEEL files in parallel
    reads: list[collections.abc.Coroutine[Any, Any, bytes]] = []
    metadata_keys: list[tuple[str, str]] = []  # (side, filename)
    for diff in metadata_diffs:
        reads.append(upstream.read(diff.filename))
        metadata_keys.append(("upstream", diff.filename))
        reads.append(downstream.read(diff.filename))
        metadata_keys.append(("downstream", diff.filename))

    if has_cross_metadata:
        reads.append(upstream.read(upstream_metadata))
        metadata_keys.append(("upstream", upstream_metadata))
        reads.append(downstream.read(downstream_metadata))
        metadata_keys.append(("downstream", downstream_metadata))

    # Track all remaining reads as (side, filename) so that entries
    # with the same filename on both sides don't collide in a dict.
    extra_keys: list[tuple[str, str]] = []
    for side_name, record_path, infos, rz in [
        ("upstream", upstream_record, upstream_infos, upstream),
        ("downstream", downstream_record, downstream_infos, downstream),
    ]:
        if record_path in infos:
            reads.append(rz.read(record_path))
            extra_keys.append((side_name, record_path))

    for side_name, wheel_path, infos, rz in [
        ("upstream", upstream_wheel_path, upstream_infos, upstream),
        ("downstream", downstream_wheel_path, downstream_infos, downstream),
    ]:
        if wheel_path in infos:
            reads.append(rz.read(wheel_path))
            extra_keys.append((side_name, wheel_path))

    # Pre-fetch METADATA for platform version checks (avoid duplicates)
    queued = {fname for _, fname in metadata_keys}
    for side_name, meta_path, infos, rz in [
        ("upstream", upstream_metadata, upstream_infos, upstream),
        ("downstream", downstream_metadata, downstream_infos, downstream),
    ]:
        if meta_path in infos and meta_path not in queued:
            reads.append(rz.read(meta_path))
            extra_keys.append((side_name, meta_path))

    fetched = await asyncio.gather(*reads) if reads else []

    # Unpack metadata reads
    upstream_meta: dict[str, bytes] = {}
    downstream_meta: dict[str, bytes] = {}
    for idx, (side, fname) in enumerate(metadata_keys):
        if side == "upstream":
            upstream_meta[fname] = fetched[idx]
        else:
            downstream_meta[fname] = fetched[idx]

    if metadata_diffs or has_cross_metadata:
        result = _check_metadata(
            result,
            upstream_meta.__getitem__,
            downstream_meta.__getitem__,
        )

    # Unpack record, wheel, and platform metadata reads into per-side dicts
    upstream_extra: dict[str, bytes] = {}
    downstream_extra: dict[str, bytes] = {}
    offset = len(metadata_keys)
    for idx, (side, fname) in enumerate(extra_keys):
        if side == "upstream":
            upstream_extra[fname] = fetched[offset + idx]
        else:
            downstream_extra[fname] = fetched[offset + idx]

    result = check_records(
        result,
        upstream_infos=upstream_infos,
        downstream_infos=downstream_infos,
        upstream_record=upstream_extra.get(upstream_record),
        downstream_record=downstream_extra.get(downstream_record),
    )

    # Merge already-fetched metadata into per-side extras
    for fname, data in upstream_meta.items():
        upstream_extra.setdefault(fname, data)
    for fname, data in downstream_meta.items():
        downstream_extra.setdefault(fname, data)

    result = check_platform_abi(
        result,
        upstream_infos=upstream_infos,
        downstream_infos=downstream_infos,
        upstream_wheel=upstream_extra.get(upstream_wheel_path),
        downstream_wheel=downstream_extra.get(downstream_wheel_path),
        upstream_metadata=upstream_extra.get(upstream_metadata),
        downstream_metadata=downstream_extra.get(downstream_metadata),
    )
    return result


def _compare(
    upstream: str,
    downstream: str,
    upstream_infos: dict[str, Any],
    downstream_infos: dict[str, Any],
) -> WheelComparison:
    upstream_whl = _wheel_basename(upstream)
    downstream_whl = _wheel_basename(downstream)
    up_dist, upstream_ver_str = _parse_name_version(upstream_whl)
    down_dist, downstream_ver_str = _parse_name_version(downstream_whl)
    canonical = packaging.utils.canonicalize_name(up_dist)
    if canonical != packaging.utils.canonicalize_name(down_dist):
        raise InvalidWheelError(
            f"dist name mismatch: upstream {up_dist!r} != downstream {down_dist!r}"
        )
    up_dist = _find_dist_info_name(upstream_infos, up_dist, upstream_ver_str)
    down_dist = _find_dist_info_name(downstream_infos, down_dist, downstream_ver_str)
    # Detect virtual environments accidentally bundled into either wheel
    # and drop their files from the name sets: they are collapsed into a
    # single per-environment entry (see VenvBundle) instead of flooding
    # the per-file diff with hundreds of individual site-packages files.
    venv_bundles = _detect_venv_bundles(upstream_infos, downstream_infos)
    upstream_names = {n for n in upstream_infos if not _is_bundled_venv_file(n)}
    downstream_names = {n for n in downstream_infos if not _is_bundled_venv_file(n)}

    only_upstream = sorted(upstream_names - downstream_names)
    only_downstream = sorted(downstream_names - upstream_names)

    # Pair extension modules that differ only in ABI suffix
    # (e.g. foo.abi3.so upstream vs foo.cpython-312-x86_64-linux-gnu.so
    # downstream).  Paired modules are reclassified as NOTICE.
    paired_extensions = _pair_extension_modules(only_upstream, only_downstream)

    # Pair dist-info and .data/ files across different prefixes caused
    # by dist name casing (ImageHash vs imagehash) or local version
    # segments (1.5.0 vs 1.5.0+rhaiv.5).  Files with identical content
    # become EXPECTED; files with different content keep their original
    # severity.
    up_di = f"{up_dist}-{upstream_ver_str}.dist-info/"
    down_di = f"{down_dist}-{downstream_ver_str}.dist-info/"
    up_data = f"{up_dist}-{upstream_ver_str}.data/"
    down_data = f"{down_dist}-{downstream_ver_str}.data/"
    di_identical, _di_different = _pair_prefixed_files(
        only_upstream, only_downstream, up_di, down_di, upstream_infos, downstream_infos
    )
    data_identical, _data_different = _pair_prefixed_files(
        only_upstream, only_downstream, up_data, down_data, upstream_infos, downstream_infos
    )
    paired_identical = di_identical | data_identical

    identical: list[str] = []
    different: list[FileDiff] = []
    for fname in sorted(upstream_names & downstream_names):
        u_info = upstream_infos[fname]
        d_info = downstream_infos[fname]
        if u_info.CRC == d_info.CRC and u_info.file_size == d_info.file_size:
            identical.append(fname)
        else:
            severity, classification = _classify_file(
                fname, dist=up_dist, version=upstream_ver_str
            )
            different.append(
                FileDiff(
                    filename=fname,
                    upstream_size=u_info.file_size,
                    downstream_size=d_info.file_size,
                    upstream_crc32=u_info.CRC,
                    downstream_crc32=d_info.CRC,
                    severity=severity,
                    classification=classification,
                )
            )

    def _make_upstream_entry(fname: str) -> FileEntry:
        severity, classification = _classify_file(
            fname, dist=up_dist, version=upstream_ver_str, missing=True
        )
        if fname in paired_identical:
            severity = Severity.EXPECTED
        elif fname in paired_extensions and severity is Severity.ERROR:
            severity = Severity.NOTICE
        return FileEntry(filename=fname, severity=severity, classification=classification)

    def _make_downstream_entry(fname: str) -> FileEntry:
        severity, classification = _classify_file(
            fname, dist=down_dist, version=downstream_ver_str, missing=True
        )
        if fname in paired_identical:
            severity = Severity.EXPECTED
        elif fname in paired_extensions and severity is Severity.ERROR:
            severity = Severity.NOTICE
        return FileEntry(filename=fname, severity=severity, classification=classification)

    return WheelComparison(
        upstream=upstream,
        downstream=downstream,
        upstream_wheel=upstream_whl,
        downstream_wheel=downstream_whl,
        dist=canonical,
        upstream_dist=up_dist,
        downstream_dist=down_dist,
        upstream_version=Version(upstream_ver_str),
        downstream_version=Version(downstream_ver_str),
        only_upstream=tuple(_make_upstream_entry(fname) for fname in only_upstream),
        only_downstream=tuple(_make_downstream_entry(fname) for fname in only_downstream),
        different=tuple(different),
        identical=tuple(identical),
        venv_bundles=venv_bundles,
    )


def _normalize_version_spec(spec: str) -> str:
    """Normalize a single version string, keeping wildcards unchanged.

    PEP 440 wildcard specifiers (e.g. ``==2.0.*``, ``!=0.41.*``) are
    valid in ``Requires-Dist`` but cannot be parsed as ``Version``
    objects.  Fall back to the original string in that case.
    """
    try:
        return str(Version(spec))
    except InvalidVersion:
        return spec


def _normalize_req(raw: str) -> str:
    """Normalize a Requires-Dist entry for comparison.

    Uses ``Requirement`` to normalize whitespace, quoting, and marker
    formatting, then canonicalizes the distribution name so that
    ``typing-extensions`` and ``typing_extensions`` compare equal.
    Version specifiers are normalized through ``Version`` so that
    PEP 440 equivalent spellings like ``2021.8.17-beta.43`` and
    ``2021.8.17b43`` compare equal.  Wildcard versions (``==2.0.*``)
    are kept as-is.
    """
    req = Requirement(raw)
    req.name = packaging.utils.canonicalize_name(req.name)
    req.specifier = SpecifierSet(
        ",".join(f"{s.operator}{_normalize_version_spec(s.version)}" for s in req.specifier)
    )
    return str(req)


def _metadata_core_match(upstream_bytes: bytes, downstream_bytes: bytes) -> bool:
    """Check whether core metadata fields match between two METADATA files.

    Compares Name, Version (single-value) and Requires-Dist,
    Provides-Extra (multi-value, compared as sets with normalization).
    Name is canonicalized per PEP 503.  Requires-Dist entries are
    normalized via :func:`_normalize_req` so that cosmetic differences
    (whitespace, quoting, name spelling, order) are ignored.
    """
    upstream_meta, _ = parse_email(upstream_bytes)
    downstream_meta, _ = parse_email(downstream_bytes)

    up_name = packaging.utils.canonicalize_name(upstream_meta["name"])
    down_name = packaging.utils.canonicalize_name(downstream_meta["name"])
    if up_name != down_name:
        return False
    # Compare public versions so that local segments (e.g. 1.5.0+rhaiv.5
    # vs 1.5.0) are treated as equivalent.
    up_ver = Version(upstream_meta["version"])
    down_ver = Version(downstream_meta["version"])
    if up_ver.public != down_ver.public:
        return False

    up_extras = set(upstream_meta.get("provides_extra") or [])
    down_extras = set(downstream_meta.get("provides_extra") or [])
    if up_extras != down_extras:
        return False

    up_reqs = {_normalize_req(r) for r in upstream_meta.get("requires_dist") or []}
    down_reqs = {_normalize_req(r) for r in downstream_meta.get("requires_dist") or []}
    return up_reqs == down_reqs


def _metadata_field_diffs(
    upstream_bytes: bytes, downstream_bytes: bytes
) -> tuple[MetadataFieldDiff, ...]:
    """Return normalized set differences for repeated METADATA fields.

    Compares ``Requires-Dist`` and ``Provides-Extra`` after the same
    normalization used by :func:`_metadata_core_match` and reports the
    values present on only one side.  Fields that match (or are absent
    on both sides) are omitted, so an empty tuple means the reportable
    fields agree.
    """
    upstream_meta, _ = parse_email(upstream_bytes)
    downstream_meta, _ = parse_email(downstream_bytes)

    fields = (
        (
            "Requires-Dist",
            {_normalize_req(r) for r in upstream_meta.get("requires_dist") or []},
            {_normalize_req(r) for r in downstream_meta.get("requires_dist") or []},
        ),
        (
            "Provides-Extra",
            set(upstream_meta.get("provides_extra") or []),
            set(downstream_meta.get("provides_extra") or []),
        ),
    )

    diffs: list[MetadataFieldDiff] = []
    for field, up_values, down_values in fields:
        only_up = tuple(sorted(up_values - down_values))
        only_down = tuple(sorted(down_values - up_values))
        if only_up or only_down:
            diffs.append(MetadataFieldDiff(field, only_up, only_down))
    return tuple(diffs)


def _check_metadata(
    result: WheelComparison,
    read_upstream: collections.abc.Callable[[str], bytes],
    read_downstream: collections.abc.Callable[[str], bytes],
) -> WheelComparison:
    """Upgrade METADATA diff severity to ERROR if core fields differ.

    Handles two cases:

    * **Same dist-info prefix** (common): both METADATA files share a
      filename and appear in *result.different*.
    * **Different dist-info prefix** (e.g. local-version differs): the
      two METADATA files have different paths and appear in
      *only_upstream* / *only_downstream*.  Core fields are still
      compared and severities updated accordingly.
    """
    up_di = f"{result.upstream_dist}-{result.upstream_version}.dist-info"
    down_di = f"{result.downstream_dist}-{result.downstream_version}.dist-info"
    upstream_metadata = f"{up_di}/METADATA"
    downstream_metadata = f"{down_di}/METADATA"

    if upstream_metadata == downstream_metadata:
        # Same dist-info prefix: METADATA appears in `different`
        metadata_diffs = [
            (i, diff)
            for i, diff in enumerate(result.different)
            if diff.filename == upstream_metadata
        ]
        if not metadata_diffs:
            return result
        new_different = list(result.different)
        field_diffs: tuple[MetadataFieldDiff, ...] = ()
        for i, diff in metadata_diffs:
            upstream_bytes = read_upstream(diff.filename)
            downstream_bytes = read_downstream(diff.filename)
            if not _metadata_core_match(upstream_bytes, downstream_bytes):
                new_different[i] = dataclasses.replace(diff, severity=Severity.ERROR)
            field_diffs = field_diffs or _metadata_field_diffs(upstream_bytes, downstream_bytes)
        return dataclasses.replace(
            result,
            different=tuple(new_different),
            metadata_field_diffs=field_diffs,
        )

    # Different dist-info prefixes: METADATA split across only_upstream / only_downstream
    up_idx = next(
        (i for i, e in enumerate(result.only_upstream) if e.filename == upstream_metadata),
        None,
    )
    down_idx = next(
        (i for i, e in enumerate(result.only_downstream) if e.filename == downstream_metadata),
        None,
    )
    if up_idx is None or down_idx is None:
        return result

    upstream_bytes = read_upstream(upstream_metadata)
    downstream_bytes = read_downstream(downstream_metadata)
    severity = (
        Severity.NOTICE
        if _metadata_core_match(upstream_bytes, downstream_bytes)
        else Severity.ERROR
    )
    field_diffs = _metadata_field_diffs(upstream_bytes, downstream_bytes)

    new_only_upstream = list(result.only_upstream)
    new_only_downstream = list(result.only_downstream)
    new_only_upstream[up_idx] = dataclasses.replace(
        result.only_upstream[up_idx],
        severity=severity,
        classification=Classification.METADATA,
    )
    new_only_downstream[down_idx] = dataclasses.replace(
        result.only_downstream[down_idx],
        severity=severity,
        classification=Classification.METADATA,
    )
    return dataclasses.replace(
        result,
        only_upstream=tuple(new_only_upstream),
        only_downstream=tuple(new_only_downstream),
        metadata_field_diffs=field_diffs,
    )


def _local_zip_infos(path: pathlib.Path) -> dict[str, zipfile.ZipInfo]:
    """Extract file info from a local wheel (zipfile)."""
    with zipfile.ZipFile(path) as zf:
        return {info.filename: info for info in zf.infolist() if not info.is_dir()}


def compare_local_wheel(
    upstream: SyncRemoteZip,
    downstream_path: pathlib.Path,
) -> WheelComparison:
    """Compare a remote upstream wheel against a local downstream wheel.

    The local wheel is opened with :mod:`zipfile`.  ``zipfile.ZipInfo``
    provides ``.CRC``, ``.file_size``, ``.filename``, and ``.is_dir()``
    — the same attributes used from ``zipwire.RemoteZipInfo``.
    """
    upstream_infos = {info.filename: info for info in upstream.infolist() if not info.is_dir()}
    downstream_infos = _local_zip_infos(downstream_path)
    result = _compare(
        upstream=upstream.url,
        downstream=str(downstream_path),
        upstream_infos=upstream_infos,
        downstream_infos=downstream_infos,
    )
    up_di = f"{result.upstream_dist}-{result.upstream_version}.dist-info"
    down_di = f"{result.downstream_dist}-{result.downstream_version}.dist-info"
    with zipfile.ZipFile(downstream_path) as ds_zf:
        result = _check_metadata(result, upstream.read, ds_zf.read)
        result = check_records(
            result,
            upstream_infos=upstream_infos,
            downstream_infos=downstream_infos,
            upstream_record=_read_record(upstream_infos, upstream.read, f"{up_di}/RECORD"),
            downstream_record=_read_record(downstream_infos, ds_zf.read, f"{down_di}/RECORD"),
        )
        result = check_platform_abi(
            result,
            upstream_infos=upstream_infos,
            downstream_infos=downstream_infos,
            upstream_wheel=_read_record(upstream_infos, upstream.read, f"{up_di}/WHEEL"),
            downstream_wheel=_read_record(downstream_infos, ds_zf.read, f"{down_di}/WHEEL"),
            upstream_metadata=_read_record(upstream_infos, upstream.read, f"{up_di}/METADATA"),
            downstream_metadata=_read_record(downstream_infos, ds_zf.read, f"{down_di}/METADATA"),
        )
    return result


async def async_compare_local_wheel(
    upstream: AsyncRemoteZip,
    downstream_path: pathlib.Path,
) -> WheelComparison:
    """Async version of :func:`compare_local_wheel`."""
    upstream_infos = {info.filename: info for info in upstream.infolist() if not info.is_dir()}
    downstream_infos = _local_zip_infos(downstream_path)
    result = _compare(
        upstream=upstream.url,
        downstream=str(downstream_path),
        upstream_infos=upstream_infos,
        downstream_infos=downstream_infos,
    )
    up_di = f"{result.upstream_dist}-{result.upstream_version}.dist-info"
    down_di = f"{result.downstream_dist}-{result.downstream_version}.dist-info"
    upstream_metadata = f"{up_di}/METADATA"
    downstream_metadata = f"{down_di}/METADATA"
    upstream_record = f"{up_di}/RECORD"
    upstream_wheel_path = f"{up_di}/WHEEL"

    # Find METADATA in `different` (same-version case)
    metadata_diffs = [diff for diff in result.different if diff.filename == upstream_metadata]

    # Detect cross-version METADATA (different-version case)
    has_cross_metadata = (
        upstream_metadata != downstream_metadata
        and any(e.filename == upstream_metadata for e in result.only_upstream)
        and any(e.filename == downstream_metadata for e in result.only_downstream)
    )

    # Pre-fetch upstream METADATA, RECORD, and WHEEL files in parallel
    reads: list[collections.abc.Coroutine[Any, Any, bytes]] = []
    read_keys: list[str] = []
    for diff in metadata_diffs:
        reads.append(upstream.read(diff.filename))
        read_keys.append(diff.filename)

    if has_cross_metadata:
        reads.append(upstream.read(upstream_metadata))
        read_keys.append(upstream_metadata)

    if upstream_record in upstream_infos:
        reads.append(upstream.read(upstream_record))
        read_keys.append(upstream_record)

    if upstream_wheel_path in upstream_infos:
        reads.append(upstream.read(upstream_wheel_path))
        read_keys.append(upstream_wheel_path)

    # Pre-fetch upstream METADATA for platform version check (if not already queued)
    if upstream_metadata in upstream_infos and upstream_metadata not in read_keys:
        reads.append(upstream.read(upstream_metadata))
        read_keys.append(upstream_metadata)

    fetched = await asyncio.gather(*reads) if reads else []
    upstream_data = dict(zip(read_keys, fetched, strict=True))

    with zipfile.ZipFile(downstream_path) as ds_zf:
        result = _check_metadata(result, upstream_data.__getitem__, ds_zf.read)
        result = check_records(
            result,
            upstream_infos=upstream_infos,
            downstream_infos=downstream_infos,
            upstream_record=upstream_data.get(upstream_record),
            downstream_record=_read_record(downstream_infos, ds_zf.read, f"{down_di}/RECORD"),
        )
        result = check_platform_abi(
            result,
            upstream_infos=upstream_infos,
            downstream_infos=downstream_infos,
            upstream_wheel=upstream_data.get(upstream_wheel_path),
            downstream_wheel=_read_record(downstream_infos, ds_zf.read, f"{down_di}/WHEEL"),
            upstream_metadata=upstream_data.get(upstream_metadata),
            downstream_metadata=_read_record(downstream_infos, ds_zf.read, f"{down_di}/METADATA"),
        )
    return result
